apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: '{{ .Values.prometheusserver.name}}'
spec:
  replicas: 1
  serviceName: '{{ .Values.prometheusserver.name}}'
  selector:
    matchLabels:
      app: '{{ .Values.prometheusserver.name}}'
  template:
    metadata:
      labels:
        app: '{{ .Values.prometheusserver.name}}'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: '{{ .Values.prometheusserver.name}}'
        image: docker.io/prom/prometheus:v2.36.2
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
          items:
            - key: prometheus.yml
              path: prometheus.yml
  volumeClaimTemplates:
    - metadata:
        name: '{{ .Values.prometheusserver.name}}'
      spec:

        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

