apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.prometheusserver.name}}'
spec:
  type: '{{ .Values.prometheusservice.type}}'
  selector:
    app: '{{ .Values.prometheusserver.name}}'
  ports:
    - protocol: TCP
      port: {{ .Values.prometheusservice.port}}
      targetPort: {{ .Values.prometheusservice.targetPort}}
