apiVersion: v1
kind: PersistentVolume
metadata:
  name: '{{ .Values.pv.name}}'
  labels:
    type: '{{ .Values.pv.type}}'
spec:
  storageClassName: '{{ .Values.pv.storageClassName}}'
  capacity:
    storage: '{{ .Values.pv.storage}}'
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" 




