apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: '{{ .Values.appservice.type}}'
  selector:
   {{- include "labels" .| indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.appservice.port | int }}
      targetPort: {{ .Values.appservice.targetPort | int }}
